CREATE TABLE USERS (
    User_ID INT AUTO_INCREMENT PRIMARY KEY,
    Profile_Name VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    F_Name VARCHAR(50),
    M_Init CHAR(1),
    L_Name VARCHAR(50),
    Player_Flag BIT,
    Creator_Flag BIT
);

CREATE TABLE ITEM_CATALOG (
Catalog_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE INVENTORY (
Inventory_ID INT AUTO_INCREMENT,
Catalog_ID INT,
Name VARCHAR(100),
PRIMARY KEY (Inventory_ID, Catalog_ID),
FOREIGN KEY (Catalog_ID) REFERENCES ITEM_CATALOG(Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ITEM (
Item_ID INT AUTO_INCREMENT,
Catalog_ID INT,
Weight DECIMAL(5,2),
Overall_Quan INT,
Description TEXT,
Category VARCHAR(50),
Rarity VARCHAR(50),
Name VARCHAR(100),
C_Flag BIT,
R_Flag BIT,
WA_Flag BIT,
UI_Flag BIT,
PRIMARY KEY (Item_ID, Catalog_ID),
FOREIGN KEY (Catalog_ID) REFERENCES ITEM_CATALOG(Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE USER_EMAIL (
User_ID INT,
Email VARCHAR(100) NOT NULL,
PRIMARY KEY (User_ID, Email),
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE CREATOR_EDIT_CATALOG (
Creator_ID INT,
Catalog_ID INT,
PRIMARY KEY (Creator_ID, Catalog_ID),
FOREIGN KEY (Creator_ID) REFERENCES USERS(User_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
FOREIGN KEY (Catalog_ID) REFERENCES ITEM_CATALOG(Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE USER_EDIT_INVENTORY (
User_ID INT,
Inventory_ID INT,
Catalog_ID INT,
PRIMARY KEY (User_ID, Catalog_ID, Inventory_ID),
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
FOREIGN KEY (Inventory_ID, Catalog_ID) REFERENCES INVENTORY(Inventory_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE WEAPON_ARMOR_EQUIPPED (
Item_ID INT,
Inventory_ID INT,
Catalog_ID INT,
PRIMARY KEY (Item_ID, Catalog_ID, Inventory_ID),
FOREIGN KEY (Item_ID, Catalog_ID) REFERENCES ITEM(Item_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
FOREIGN KEY (Inventory_ID, Catalog_ID) REFERENCES INVENTORY(Inventory_ID, Catalog_ID)
);

CREATE TABLE CONTAINS_ITEM (
Inventory_ID INT,
Catalog_ID INT,
Item_ID INT,
Quantity INT,
PRIMARY KEY (Inventory_ID, Catalog_ID, Item_ID),
FOREIGN KEY (Inventory_ID, Catalog_ID) REFERENCES INVENTORY(Inventory_ID, Catalog_ID),
FOREIGN KEY (Item_ID, Catalog_ID) REFERENCES ITEM(Item_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ITEM_EFFECT (
Item_ID INT,
Catalog_ID INT,
Effect VARCHAR(100),
Constant_Inc INT,
Percent_Inc INT,
Duration INT,
PRIMARY KEY (Item_ID, Catalog_ID, Effect),
FOREIGN KEY (Item_ID, Catalog_ID) REFERENCES ITEM(Item_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ITEM_WEAPON_ARMOR_RANGE (
Item_ID INT,
Catalog_ID INT,
Range INT,
Damage INT,
PRIMARY KEY (Item_ID, Catalog_ID, Range),
FOREIGN KEY (Item_ID, Catalog_ID) REFERENCES ITEM(Item_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ITEM_WEAPON_ARMOR_TYPE (
Item_ID INT,
Catalog_ID INT,
Type VARCHAR(50),
PRIMARY KEY (Item_ID, Catalog_ID, Type),
FOREIGN KEY (Item_ID, Catalog_ID) REFERENCES ITEM(Item_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE CRAFTING_RECIPE (
Item_ID_Output INT,
Catalog_ID_Output INT,
Item_ID_Input INT,
Catalog_ID_Input INT,
Quantity INT,
PRIMARY KEY (Item_ID_Output, Catalog_ID_Output, Item_ID_Input, Catalog_ID_Input),
FOREIGN KEY (Item_ID_Output, Catalog_ID_Output) REFERENCES ITEM (Item_ID, Catalog_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
FOREIGN KEY (Item_ID_Input, Catalog_ID_Input) REFERENCES ITEM (Item_ID, Catalog_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);